import { Page, BrowserContext } from 'playwright';
import * as fs from 'fs';
import * as path from 'path';

// Helper to log to the main process
const log = (msg: string) => console.error(JSON.stringify({ type: 'log', message: msg, timestamp: new Date().toISOString() }));

export async function runScraperAndPublish(
  context: BrowserContext, 
  targetUrl: string, 
  prompt: string
): Promise<any> {
  
  // 1. Scraper Phase
  log(`[Agent] Navigating to target: ${targetUrl}`);
  const page = await context.newPage();
  await page.goto(targetUrl, { waitUntil: 'domcontentloaded' });
  
  // Simulate AI "Thinking" and interacting
  log(`[Agent] Analyzing page content based on prompt: "${prompt}"...`);
  await page.waitForTimeout(2000); 

  // In a real AI implementation, we would extract text here. 
  // For now, we capture the visual context as the "Content".
  const title = await page.title();
  log(`[Agent] Extracted page title: ${title}`);

  // Take a screenshot to use for the XHS post
  const tmpDir = path.join(process.cwd(), 'tmp_assets');
  if (!fs.existsSync(tmpDir)) fs.mkdirSync(tmpDir, { recursive: true });
  
  const screenshotPath = path.join(tmpDir, `screenshot_${Date.now()}.png`);
  await page.screenshot({ path: screenshotPath, fullPage: false });
  log(`[Agent] Screenshot saved to: ${screenshotPath}`);

  await page.close();

  // 2. XHS Publishing Phase
  // Note: This assumes the user is ALREADY logged in to XHS in this browser context,
  // or we will pause to let them login if detected.
  
  log(`[Agent] Opening Xiaohongshu Creator Studio...`);
  const xhsPage = await context.newPage();
  await xhsPage.goto('https://creator.xiaohongshu.com/publish/publish', { waitUntil: 'domcontentloaded' });

  // Check for login
  const isLoggedOut = await xhsPage.isVisible('text=登录'); // Simple heuristic
  if (isLoggedOut) {
    log(`[Agent] WARN: You are not logged in to Xiaohongshu. Please login manually in the window.`);
    // In a real headless tool, we might wait for login success or cookie injection.
    // For this desktop app (headed), the user can see it.
    await xhsPage.waitForTimeout(5000); // Give some time, but likely will fail if fully automated
  }

  log(`[Agent] Uploading screenshot...`);
  
  // Use the file chooser to upload
  // XHS input selector might vary, looking for the file input
  try {
    // This selector is brittle and depends on XHS implementation
    const fileInput = await xhsPage.waitForSelector('input[type="file"]', { timeout: 5000 });
    if (fileInput) {
        await fileInput.setInputFiles(screenshotPath);
    }
  } catch (e) {
      log(`[Agent] Error finding upload button: ${e}`);
  }

  log(`[Agent] Generating content...`);
  // Fill Title
  try {
      const titleInput = await xhsPage.locator('input[placeholder*="标题"]'); // Loose selector
      await titleInput.fill(`[AI Share] ${title}`);
  } catch (e) {
      log(`[Agent] Could not find title input (might need manual intervention)`);
  }

  // Fill Content
  try {
      // Content is often a div contenteditable or textarea
      const contentInput = await xhsPage.locator('#post-textarea'); 
      if (await contentInput.count() > 0) {
        await contentInput.fill(`Generated by HyperAgent.\nSource: ${targetUrl}\nPrompt: ${prompt}`);
      } else {
        // Fallback for contenteditable div usually found in rich text editors
        await xhsPage.keyboard.type(`Generated by HyperAgent.\nSource: ${targetUrl}\nPrompt: ${prompt}`);
      }
  } catch (e) {
      log(`[Agent] Could not fill content`);
  }

  log(`[Agent] Ready to publish. Waiting for user confirmation (Simulated)...`);
  await xhsPage.waitForTimeout(3000);

  // cleanup
  // await xhsPage.close(); 
  // We leave it open for the user to click "Publish" manually to avoid spamming XHS.

  return {
    screenshot: screenshotPath,
    xhs_status: 'ready_to_publish'
  };
}
